"""empty message

Revision ID: 1e10d7968b8a
Revises: 695a6d00db25
Create Date: 2020-09-24 20:54:56.948324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e10d7968b8a'
down_revision = '695a6d00db25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_comment', sa.Column('parent_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_comment', 'parent_id')
    # ### end Alembic commands ###
