"""empty message

Revision ID: 21e07e84e024
Revises: 72964a6ed720
Create Date: 2020-09-24 16:02:53.767467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e07e84e024'
down_revision = '72964a6ed720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('slogan', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'slogan')
    # ### end Alembic commands ###
