"""empty message

Revision ID: 72964a6ed720
Revises: 1c8a57c7943d
Create Date: 2020-09-24 13:57:53.518585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72964a6ed720'
down_revision = '1c8a57c7943d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('recent_login', sa.DateTime(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False,
               comment='user password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True,
               comment=None,
               existing_comment='user password')
    op.drop_column('user', 'recent_login')
    # ### end Alembic commands ###
