"""empty message

Revision ID: 91441825ef98
Revises: 
Create Date: 2020-09-27 09:49:52.571040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91441825ef98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='login record'),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('login_add', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_log')
    # ### end Alembic commands ###
