"""empty message

Revision ID: 9505d8979ba4
Revises: 91441825ef98
Create Date: 2020-09-27 10:35:37.381726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9505d8979ba4'
down_revision = '91441825ef98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_log', sa.Column('read_add', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_log', 'read_add')
    # ### end Alembic commands ###
