"""empty message

Revision ID: a2043c4168ed
Revises: f6087533d040
Create Date: 2020-09-27 10:38:32.492123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2043c4168ed'
down_revision = 'f6087533d040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_log', sa.Column('login_addr', sa.String(length=100), nullable=True))
    op.add_column('login_log', sa.Column('real_addr', sa.String(length=100), nullable=True))
    op.drop_column('login_log', 'login_add')
    op.drop_column('login_log', 'real_add')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_log', sa.Column('real_add', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('login_log', sa.Column('login_add', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('login_log', 'real_addr')
    op.drop_column('login_log', 'login_addr')
    # ### end Alembic commands ###
