"""empty message

Revision ID: a2489d0aaec6
Revises: 21e07e84e024
Create Date: 2020-09-24 16:34:50.074761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2489d0aaec6'
down_revision = '21e07e84e024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_info', sa.Column('user_ip', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('love_info', 'user_ip')
    # ### end Alembic commands ###
