"""empty message

Revision ID: aed42d17280b
Revises: a2043c4168ed
Create Date: 2020-09-27 11:04:15.292805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed42d17280b'
down_revision = 'a2043c4168ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_comment', sa.Column('delete_flag', sa.INTEGER(), nullable=True, comment='this comment delete flag 0 no 1 yes'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_comment', 'delete_flag')
    # ### end Alembic commands ###
