"""empty message

Revision ID: bc6cbd4c9612
Revises: fc1bb298cc5c
Create Date: 2020-09-23 16:46:32.344331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6cbd4c9612'
down_revision = 'fc1bb298cc5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loveme',
    sa.Column('id', sa.INTEGER(), nullable=False, comment='primary key id'),
    sa.Column('counts', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loveme')
    # ### end Alembic commands ###
