"""empty message

Revision ID: d2f807e6bc46
Revises: 412ccc5e3c11
Create Date: 2020-09-27 13:37:26.531223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2f807e6bc46'
down_revision = '412ccc5e3c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_comment', sa.Column('blog_id', sa.INTEGER(), nullable=True))
    op.drop_constraint('blog_comment_ibfk_2', 'blog_comment', type_='foreignkey')
    op.create_foreign_key(None, 'blog_comment', 'blog', ['blog_id'], ['id'])
    op.drop_column('blog_comment', 'photo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_comment', sa.Column('photo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blog_comment', type_='foreignkey')
    op.create_foreign_key('blog_comment_ibfk_2', 'blog_comment', 'blog', ['photo_id'], ['id'])
    op.drop_column('blog_comment', 'blog_id')
    # ### end Alembic commands ###
