"""empty message

Revision ID: f6087533d040
Revises: 9505d8979ba4
Create Date: 2020-09-27 10:38:15.771916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6087533d040'
down_revision = '9505d8979ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='login record'),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('login_add', sa.String(length=100), nullable=True),
    sa.Column('real_add', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_log')
    # ### end Alembic commands ###
